# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('Quando_Foi_Encontrado', models.DateField(verbose_name='Data ')),
                ('Lugar_Onde_Foi_Achado', models.CharField(max_length=35)),
                ('foto_capa', models.ImageField(upload_to='images')),
                ('tipo', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
    ]
